const store = require('../../utils/store')
Page({
  data: { id: '', name: '', teacher: '', location: '', weekdayIndex: 0, dayNames: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'], timingMode: 'period', periodNames: [], startPeriodIndex: 0, endPeriodIndex: 0, customStart: '16:40', customEnd: '18:10', startWeek: 1, endWeek: 18, reminderMinutes: 30 },
  onLoad(options) { const document = store.load(); this.setData({ periodNames: document.periods.map(item => '第 ' + item.index + ' 节') }); if (options.id) { const item = document.courses.find(course => course.id === options.id); if (item) this.setData({ id: item.id, name: item.name, teacher: item.teacher, location: item.location, weekdayIndex: item.weekday - 1, timingMode: item.timingMode, startPeriodIndex: (item.startPeriod || 1) - 1, endPeriodIndex: (item.endPeriod || 1) - 1, customStart: item.customStart || '16:40', customEnd: item.customEnd || '18:10', startWeek: item.startWeek, endWeek: item.endWeek, reminderMinutes: item.reminderMinutes }) } },
  field(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }) },
  dayChange(event) { this.setData({ weekdayIndex: Number(event.detail.value) }) },
  modeChange(event) { this.setData({ timingMode: event.currentTarget.dataset.mode }) },
  startPeriodChange(event) { this.setData({ startPeriodIndex: Number(event.detail.value) }) },
  endPeriodChange(event) { this.setData({ endPeriodIndex: Number(event.detail.value) }) },
  timeChange(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }) },
  save() { if (!this.data.name.trim()) { wx.showToast({ title: '请填写课程名称', icon: 'none' }); return } const document = store.load(); const old = document.courses.find(item => item.id === this.data.id); const course = { id: this.data.id || 'course-' + Date.now(), name: this.data.name.trim(), teacher: this.data.teacher, location: this.data.location, notes: old ? old.notes : '', color: old ? old.color : '#1677ff', weekday: this.data.weekdayIndex + 1, timingMode: this.data.timingMode, startPeriod: this.data.timingMode === 'period' ? this.data.startPeriodIndex + 1 : null, endPeriod: this.data.timingMode === 'period' ? this.data.endPeriodIndex + 1 : null, customStart: this.data.timingMode === 'custom' ? this.data.customStart : '', customEnd: this.data.timingMode === 'custom' ? this.data.customEnd : '', startWeek: this.data.startWeek, endWeek: this.data.endWeek, reminderMinutes: this.data.reminderMinutes }; const index = document.courses.findIndex(item => item.id === course.id); if (index >= 0) document.courses[index] = course; else document.courses.push(course); store.save(document); wx.navigateBack() }
})
